title: Joseph Chen
description: Embedded Systems Firmware Engineer
baseurl: ""
url: https://josepho0918.github.io

theme: cvless

# site settings
taglong: Embedded Systems Firmware Engineer
tagshort: Firmware Engineer
cv: true

# author settings
author:
  name: Joseph Chen
  email: joseph@baoruh.com.tw
joblines:
  - Firmware Engineer
  - Baoruh Electronics Co., Ltd.
photo: assets/files/photo.png
address: No. 285, Dingciang Street, Kaohsiung, 80790 Taiwan
phone: +886 7 3472000

# profile links
profile:
  github: https://github.com/josepho0918
  linkedin: https://www.linkedin.com/in/josepho0918

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
