title: Joseph Chen
description: Embedded Systems Firmware Engineer
baseurl: ""
url: https://josepho0918.github.io

theme: cvless

# site settings
taglong: Embedded Systems Firmware Engineer
tagshort: Firmware Engineer

# author settings
author:
  name: Joseph Chen
  email: joseph@baoruh.com.tw
photo: assets/files/photo.png
address: No. 285, Dingciang Street, Kaohsiung, 80790 Taiwan
phone: +886 7 3472000

# social media links
social:
  github: josepho0918
  linkedin: josepho0918

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
